export const DJT_RULES_ARTICLE = {
  id: "djt-quest-rules",
  title: "DJT Quest — Regras de Pontuacao e Mecanicas",
  summary:
    "Resumo oficial das regras de pontuacao, fluxos e bonus do DJT Quest para consultas no StudyLab.",
  body: [
    "## Visao geral",
    "O DJT Quest combina aprendizado tecnico com gamificacao. O XP vem de quizzes, campanhas, desafios, foruns, SEPBook e avaliacoes. As regras podem evoluir; esta pagina documenta o estado atual.",
    "",
    "## SEPBook",
    "- Publicacoes completas somam XP.",
    "- Comentarios ricos (com contexto, hashtags e marcacoes) podem gerar XP adicional.",
    "- Acoes avaliadas por lideres podem converter resultados em XP adicional.",
    "",
    "## Quizzes",
    "- Cada quiz define o XP total e o valor de cada pergunta.",
    "- O XP e contabilizado conforme o desempenho nas perguntas.",
    "- Quizzes passam por curadoria quando habilitada.",
    "",
    "## Foruns",
    "- Relatos e solucoes relevantes geram reconhecimento.",
    "- Ha bonus mensal para perfis com maior impacto no forum (quando o bonus estiver ativo).",
    "",
    "## Campanhas e desafios",
    "- Campanhas conectam quizzes, foruns e acoes em um periodo.",
    "- Desafios podem exigir evidencias e validacao; ao concluir, o XP definido e creditado.",
    "",
    "## Avaliacoes",
    "- Lideres avaliam criterios como contexto, seguranca, resultado e aprendizado.",
    "- Avaliacoes alimentam o XP e ajudam a calibrar o ranking.",
    "",
    "## Bonus e rankings",
    "- Bonus especiais podem ser aplicados pela gestao (admin).",
    "- Rankings usam XP total e indicadores de engajamento.",
    "",
    "## Observacoes",
    "- Regras podem ser ajustadas por campanhas ou diretrizes internas.",
    "- Em caso de duvida, consulte o Studio (curadoria) ou seu lider.",
  ].join("\n"),
  outline: [
    { title: "Visao geral" },
    { title: "SEPBook" },
    { title: "Quizzes" },
    { title: "Foruns" },
    { title: "Campanhas e desafios" },
    { title: "Avaliacoes" },
    { title: "Bonus e rankings" },
    { title: "Observacoes" },
  ],
  tags: ["djt", "regras", "xp", "pontuacao", "quiz", "forum", "sepbook", "campanhas"],
};
